openapi: 3.0.0
info:
  title: aurora-backend-restapi
  version: "1.0"
servers:
  - url: "https://api.auroradao-dev.tk"
    description: dev
  - url: "https://api.auroradao.org"
    description: prod
paths:
  /ad:
    post:
      summary: Upload Ad
      operationId: post-ad
      responses:
        "200":
          description: Ad Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Metadata"
        "400":
          description: Missing Required Information
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AdInput"
            examples: {}
      parameters: []
  "/ad/{account}/{metadata}":
    get:
      responses:
        "200":
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Metadata"
    parameters:
      - schema:
          type: string
        name: account
        in: path
        required: true
        description: account address hex string
      - schema:
          type: string
        name: metadata
        in: path
        required: true
  /post:
    post:
      summary: Upload Post
      operationId: post-post
      responses:
        "200":
          description: Post Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Metadata"
        "400":
          description: Missing Required Information
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostInput"
            examples: {}
      parameters: []
    parameters: []
  "/right/{postId}":
    get:
      responses:
        "200":
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Owner"
    parameters:
      - schema:
          type: string
        name: postId
        in: path
        required: true
        description: postId
components:
  schemas:
    Metadata:
      description: ""
      type: object
      properties:
        metadata:
          type: string
          minLength: 1
      required:
        - metadata
    Owner:
      description: ""
      type: object
      properties:
        owner:
          type: string
          minLength: 0
          description: Owner of DistributionRight
    AdSpecifications:
      title: AdSpecifications
      type: object
      properties:
        width:
          type: integer
        height:
          type: integer
        link:
          type: string
      required:
        - width
        - height
    PostInput:
      title: PostInput
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        key_visual:
          type: string
        ad_specifications:
          $ref: "#/components/schemas/AdSpecifications"
        images:
          type: array
          items:
            type: string
      required:
        - name
        - description
        - key_visual
        - ad_specifications
        - images
    AdInput:
      title: AdInput
      type: object
      properties:
        image:
          type: string
        link:
          type: string
        alt:
          type: string
      required:
        - image
        - link
        - alt
        - images
  securitySchemes:
    APIKey:
      name: API Key
      type: apiKey
      in: header
  responses: {}
security:
  - API Key - 1: []
