openapi: 3.0.0
info:
  title: kaleido-backend-restapi
  version: "1.0"
servers:
  - url: "https://api.kaleido-dev.tk"
    description: dev
  - url: "https://api.kaleido.org"
    description: prod
paths:
  /post:
    post:
      summary: Upload Post
      operationId: post-post
      responses:
        "200":
          description: Post Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Metadata"
        "400":
          description: Missing Required Information
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostInput"
            examples: {}
      parameters: []
    parameters: []
components:
  schemas:
    Metadata:
      description: ""
      type: object
      properties:
        metadata:
          type: string
          minLength: 1
      required:
        - metadata
    AdSpecifications:
      title: AdSpecifications
      type: object
      properties:
        width:
          type: integer
        height:
          type: integer
        link:
          type: string
      required:
        - width
        - height
    PostInput:
      title: PostInput
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        key_visual:
          type: string
        ad_specifications:
          $ref: "#/components/schemas/AdSpecifications"
      required:
        - name
        - description
        - key_visual
        - ad_specifications
  securitySchemes:
    APIKey:
      name: API Key
      type: apiKey
      in: header
  responses: {}
security:
  - API Key - 1: []
